version: '3.8'

services:
  backend:
    build: ./storyst-backend
    container_name: storyst-backend-app
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    
    restart: unless-stopped