FROM node:22-alpine
WORKDIR /app
COPY storyst-backend/package*.json ./
RUN npm install
COPY storyst-backend/ .
RUN mkdir -p generated/prisma
RUN npx prisma generate
RUN npx tsc
EXPOSE 3001
CMD ["node", "dist/app/app.js"]